name: flexi
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  bloc: ^9.0.0
  firebase_core: ^3.15.2
  firebase_crashlytics: ^4.3.10
  firebase_messaging: ^15.2.10
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get: ^4.7.2
  http: ^1.5.0


dev_dependencies:
  lint: ^2.8.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
