// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8jKqo_-sZ6bFGvTXS8AJstiRXJta1ZQI',
    appId: '1:539269697373:web:df7ad4842c6936288222b4',
    messagingSenderId: '539269697373',
    projectId: 'flexi-f8f69',
    authDomain: 'flexi-f8f69.firebaseapp.com',
    storageBucket: 'flexi-f8f69.firebasestorage.app',
    measurementId: 'G-3TEDGXFSZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWVmCMf4eYTHIGKXoCsz8uiTFVA0MXtPw',
    appId: '1:539269697373:android:bdde437e02305cae8222b4',
    messagingSenderId: '539269697373',
    projectId: 'flexi-f8f69',
    storageBucket: 'flexi-f8f69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDut7-3QzsjVILefXGB33hy8qmBjTcqbn8',
    appId: '1:539269697373:ios:9894b9aaa16e03728222b4',
    messagingSenderId: '539269697373',
    projectId: 'flexi-f8f69',
    storageBucket: 'flexi-f8f69.firebasestorage.app',
    iosBundleId: 'com.apps.flexi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDut7-3QzsjVILefXGB33hy8qmBjTcqbn8',
    appId: '1:539269697373:ios:9894b9aaa16e03728222b4',
    messagingSenderId: '539269697373',
    projectId: 'flexi-f8f69',
    storageBucket: 'flexi-f8f69.firebasestorage.app',
    iosBundleId: 'com.apps.flexi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8jKqo_-sZ6bFGvTXS8AJstiRXJta1ZQI',
    appId: '1:539269697373:web:3bba24c45f4c70ec8222b4',
    messagingSenderId: '539269697373',
    projectId: 'flexi-f8f69',
    authDomain: 'flexi-f8f69.firebaseapp.com',
    storageBucket: 'flexi-f8f69.firebasestorage.app',
    measurementId: 'G-GC287JFFWT',
  );
}
